export const LOAD_SEARCH_RESULT_MOVIES = 'movies/SearchResult/LOAD_SEARCH_RESULT_MOVIES';
export const LOAD_SEARCH_RESULT_MOVIES_SUCCESS = 'movies/SearchResult/LOAD_SEARCH_RESULT_MOVIES_SUCCESS';
export const LOAD_SEARCH_RESULT_MOVIES_ERROR = 'movies/SearchResult/LOAD_SEARCH_RESULT_MOVIES_ERROR';
